In [2]:
import torch
import torchvision
import torch.nn as nn
'''  do not forget =    it's (HEIGHT, WIDTH)    ''' 
import torch.nn.functional as F
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
torch.set_printoptions(linewidth = 120)
torch.set_grad_enabled(True)
import os
import numpy as np

In [3]:

foo = np.array(np.load("numpy/one_two_shuffled.npy"))


def convert_all_to_float(arr):
    for i in range (len(arr)):
        arr_float = arr[i][0].astype(np.float)
        arr[i][0] = arr_float
    print ("conversion  to float successful !")
    



def chug_to_tensor(images,labels):
    images = torch.from_numpy(images)
    labels = torch.FloatTensor(labels)
    images = images.unsqueeze(0)
    images = images.unsqueeze(0)
    labels = labels.unsqueeze(0)
    images = images.type(torch.float32)
    
    return (images,labels)

def convert(arr):
    batch = next(iter(arr))
    image, label = batch
    image = torch.from_numpy(image)
    label = torch.Tensor(label)
    image = image.unsqueeze(0)
    image = image.unsqueeze(0)
    label = label.unsqueeze(0)
    image = image.type(torch.float32)
    

    
    
    arr_element = ([image, label])
    
    print (arr_element)

# foo is rea

convert_all_to_float(foo)

conversion  to float successful !


In [4]:
## experimentation -- move on bois  nothing to see here
peanut = foo

print (peanut[0])

single_batch = next(iter(peanut))

for single_batch in peanut:
    
    image, label = single_batch
    
    image,label = chug_to_tensor(image, label)
    print (image,label)

[array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])
 list([2])]
tensor([[[[255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          ...,
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.]]]]) tensor([[2.]])
tensor([[[[254., 254., 254.,  ..., 254., 254., 254.],
          [254., 254., 254.,  ..., 254., 254., 254.],
          [254., 254., 254.,  ..., 254., 254., 254.],
          ...,
          [254., 254., 254.,  ..., 254., 254., 254.],
          [254., 254., 254.,  ..., 254., 254., 254.],
          [254., 254., 254.,  ..

          [245., 245., 245.,  ..., 245., 245., 245.]]]]) tensor([[1.]])
tensor([[[[255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          ...,
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.]]]]) tensor([[2.]])
tensor([[[[255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          ...,
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.],
          [255., 255., 255.,  ..., 255., 255., 255.]]]]) tensor([[1.]])
tensor([[[[246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          [246., 246., 246.,  ..., 246., 246., 246.],
          ...,
          [246., 246., 246.,  ..., 24

In [5]:

train_loader = DataLoader( peanut, batch_size = 1)

    
print (train_loader)




In [14]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.conv1 = nn.Conv2d(1, 6, 5)   ## conv layers 
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        
        self.fc1 = nn.Linear(7744, 120)   # linear layers 
        self.fc2 = nn.Linear(120, 84)
        self.out = nn.Linear(84, 1)     # final out channel

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        
        x = x.view(-1, 7744)  ## reshape thingy
        
        x = torch.relu(self.fc1(x))
        x = F.softmax(self.fc2(x), dim = 0)  # let this be softmax, relu exploded the loss 
        
        ##  loss isnt exploding
        
        x = self.out(x)
        return x


net = Net()

In [29]:
optimizer = optim.Adam(net.parameters(), lr = 0.1)
    
#loss_func = torch.nn.MSELoss(pred, label)

loss_func = torch.nn.SmoothL1Loss(pred, label)


#loss_func = torch.nn.NLLLoss(pred, label)

## ALL CLEAR AND WORKING 

In [15]:
single_batch = next(iter(peanut))

image, label = single_batch

image,label = chug_to_tensor(image, label)

print (net(image))

tensor([[-0.1263]], grad_fn=<AddmmBackward>)


In [23]:

epoch_loss = 0

single_batch = next(iter(peanut))

for single_batch in peanut:
    
    
    image, label = single_batch
    
    optimizer.zero_grad()
    
    image,label = chug_to_tensor(image, label)
    
    pred = net(image)
    
    
    
#     print (pred, label)
    
    #########################################  ALL GOOD so far
    
    loss = loss_func(pred, label)
    
    print (loss)
    
    loss.backward()
    
    optimizer.step()
    
    epoch_loss += loss
    

print ("EPOCH_LOSS  = ", epoch_loss)
    
    
    


RuntimeError: the derivative for 'weight' is not implemented

In [31]:
## LOOPER


epochs = 100
for m in range (epochs):
    
    epoch_loss = 0

    single_batch = next(iter(peanut))

    for single_batch in peanut:


        image, label = single_batch

        optimizer.zero_grad()

        image,label = chug_to_tensor(image, label)

        pred = net(image)

        
        
        
        #########################################  ALL GOOD so far

        loss = loss_func(pred, label)

#         print (loss)

        loss.backward()

        optimizer.step()

        epoch_loss += loss


    print (m+1, "EPOCH_LOSS  = ", epoch_loss)

    
    


1 EPOCH_LOSS  =  tensor(141.9496, grad_fn=<AddBackward0>)
2 EPOCH_LOSS  =  tensor(121.3871, grad_fn=<AddBackward0>)
3 EPOCH_LOSS  =  tensor(160.6187, grad_fn=<AddBackward0>)
4 EPOCH_LOSS  =  tensor(107.4192, grad_fn=<AddBackward0>)
5 EPOCH_LOSS  =  tensor(137.2965, grad_fn=<AddBackward0>)
6 EPOCH_LOSS  =  tensor(133.5340, grad_fn=<AddBackward0>)
7 EPOCH_LOSS  =  tensor(117.3185, grad_fn=<AddBackward0>)
8 EPOCH_LOSS  =  tensor(152.2480, grad_fn=<AddBackward0>)
9 EPOCH_LOSS  =  tensor(116.4184, grad_fn=<AddBackward0>)
10 EPOCH_LOSS  =  tensor(146.2940, grad_fn=<AddBackward0>)
11 EPOCH_LOSS  =  tensor(140.7435, grad_fn=<AddBackward0>)
12 EPOCH_LOSS  =  tensor(119.5157, grad_fn=<AddBackward0>)
13 EPOCH_LOSS  =  tensor(168.4282, grad_fn=<AddBackward0>)
14 EPOCH_LOSS  =  tensor(126.6600, grad_fn=<AddBackward0>)


KeyboardInterrupt: 

In [38]:
ep = str(epochs)

name = "models/"+ep+ "_sneakernet_adam_smoothl1.MODEL"
torch.save(net, name)